### ISSUE TITLE
FreeTVuz

### ISSUE THREAD

**Issue by Adidasuz** [phstudio2/FreeTV#1]
FreeTVuz qanday qilib sayit yaratiladi?
[bulk-sponsorships-template (1).xlsx](https://github.com/phstudio2/FreeTV/files/13821404/bulk-sponsorships-template.1.xlsx)

**Comment by pa238** [comment]
Could you please ask the question in the English language?

**Comment by pa238** [comment]
Due to inactivity, I am closing this issue.
