### ISSUE TITLE
better playlist for German stations

### ISSUE THREAD

**Issue by SamHawkens** [phstudio2/FreeTV#4]
FreeTV works great, thanks for this app!

The current playlist supports only very few TV stations from Germany. And some of the channels do not work at all.

Kodinerds is most likely the best place for german playlists. Could you maybe add these?
[main stations](https://github.com/jnk22/kodinerds-iptv/blob/master/iptv/kodi/kodi_tv_main.m3u)
[regional stations](https://github.com/jnk22/kodinerds-iptv/blob/master/iptv/kodi/kodi_tv_regional.m3u)

**Comment by pa238** [comment]
Added in [version 1.2](https://github.com/phstudio2/FreeTV/releases/tag/1.2), thank you for your support.

**Comment by SamHawkens** [comment]
works like a charm, thanks a lot!
