### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by qorrymarzuki** [phstudio2/FreeTV#5]
The app is superb, however there are inconvenient issues when I'm using the app:
1. Lack of countries
2. Unable to create our own category for channels
3. Lack of stream media controls
4. Not a proper dark mode (it's blue mode)

It would be great if these features are added:
1. Let us add our own stream link in the meantime and save it
2. Let us make our own categories of channels
3. Add basic media control (volume, brightness, change resolution, pop-up player)
4. Add material you feature

**Comment by pa238** [comment]
1. We are gradually working to add new countries.
2. Added in [version 1.4](https://github.com/phstudio2/FreeTV/releases/tag/1.4)
3. Added in [version 1.5](https://github.com/phstudio2/FreeTV/releases/tag/1.5)
4. Maybe in the future.

Thank you for your support. If you like our work please support us via [PayPal](http://paypal.me/PHstudio2).
