### ISSUE TITLE
Add support for more TV channels

### ISSUE THREAD

**Issue by Tarek-Hasan** [phstudio2/FreeTV#7]
Hi, you can add following IPTV playlists to your app or add a button to download and use these.
- [Free TV](https://github.com/Free-TV/IPTV) : This list has good quality mainstream free channels.
- [iptv-org](https://github.com/iptv-org/iptv) : One of the largest collection of publicly available IPTV channels from all over the world. It also has [API](https://github.com/iptv-org/api) support.

**Comment by pa238** [comment]
Thank you for your interest in improving our application. We already use both of these lists in our application.
